
from csvkit.exceptions import CustomException


class ArgumentErrorTK(CustomException):
    """
    Exception raised when the user supplies an invalid column identifier.
    """
    pass

